### PR TITLE
update: binary urls

### PR DESCRIPTION
**Pull request by jroehl**

### CODE REVIEW

**Comment by NicolasRitouet** [comment]
@jroehl there's been a new update: https://www.docdroid.net/96B4kBA/releasenotes-201810.pdf#page=82

**Comment by jroehl** [comment]
That's what this pr is about - just updated the urls to the new version ...

**Comment by NicolasRitouet** [comment]
@jroehl can you gitignore `yarn.lock`?

**Review by NicolasRitouet — APPROVED** [review]

**Pull request merged**
